# SPDX-FileCopyrightText: Copyright (c) 2025 The Newton Developers
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ==============================================================================
# Default pipeline configuration
# ==============================================================================
default:
  interruptible: true
  # Only retry on GitLab failures (not on script failures for example)
  retry:
    max: 2
    when:
      - api_failure
      - runner_system_failure
      - stuck_or_timeout_failure
      - scheduler_failure
      - unknown_failure

variables:
  UV_LINK_MODE: copy

workflow:
  rules:
    - if: $CI_PROJECT_ROOT_NAMESPACE != "omniverse" # Prevent pipelines that can't access the runners
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_SHA
    - if: $CI_PIPELINE_SOURCE == "schedule" || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      auto_cancel:
        on_new_commit: none
        on_job_failure: none
    - if: $CI_COMMIT_TAG # Run for tagged releases
    - if: $CI_COMMIT_BRANCH =~ /^release-.*/
    - if: $CI_PIPELINE_SOURCE == "web" # Run if triggered from the UI

stages:
  - lint
  - test
  - build
  - docs

# ==============================================================================
# Include the Omniverse DevPlat runner job definitions
# ==============================================================================
include:
  - project: "omniverse/devplat/gitlab/templates/runners"
    file: "/modules/include.yml"
    ref: v2_latest

# --- Stage: Lint ---
linting:
  stage: lint
  image: ghcr.io/astral-sh/uv:bookworm
  extends:
    - .omni_nvks_micro_runner
  needs: []
  script:
    - uvx pre-commit run --all-files --show-diff-on-failure

# --- Stage: Test ---

.test_common:
  stage: test
  needs: []
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    paths:
      - rspec.xml
      - coverage.xml
    reports:
      junit: rspec.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH =~ /^release-.*/
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      changes:
        - .gitlab/ci/*
        - .gitlab-ci.yml
        - newton/**/*
        - pyproject.toml
        - .python-version
        - uv.lock
    - when: manual # If not auto-triggered, allow any pipeline to run this job manually
      allow_failure: true
  script:
    - uv run --extra dev --extra torch-cu12 -m newton.tests --junit-report-xml rspec.xml --coverage --coverage-xml coverage.xml

linux-x86_64 test:
  image: ghcr.io/astral-sh/uv:bookworm
  extends:
    - .ipp_lnx_x86_64_gpu
    - .test_common

# TODO: mujoco load dll often fails on Windows, disabling
.windows-x86_64 test:
  extends:
    - .test_common
  needs: []
  before_script:
    - powershell -ExecutionPolicy ByPass -c {$env:UV_INSTALL_DIR = "${env:CI_PROJECT_DIR}\uv-install";irm https://astral.sh/uv/install.ps1 | iex}
    - $env:Path = "${env:CI_PROJECT_DIR}\uv-install;$env:Path"
    - uv venv --managed-python
  allow_failure: true
  tags:
    - win-x86_64-gpu-1x-573.42

linux-x86_64 test warp nightly:
  image: ghcr.io/astral-sh/uv:bookworm
  extends:
    - .ipp_lnx_x86_64_gpu
  stage: test
  needs: []
  artifacts:
    when: always
    paths:
      - rspec.xml
    reports:
      junit: rspec.xml
  before_script:
    - uv venv
    - source .venv/bin/activate
    - uv sync --extra dev --extra torch-cu12
    - uv pip install -U --pre warp-lang
  script:
    - python -m newton.tests --junit-report-xml rspec.xml
  allow_failure: true # TODO: Remove this after outstanding issues are resolved

# --- Stage: Build ---
build_package:
  stage: build
  image: ghcr.io/astral-sh/uv:bookworm
  needs: []
  extends:
    - .ipp_lnx_x86_64_cpu_micro
  script:
    - uv build --wheel
    - uvx twine check dist/*
  artifacts:
    paths:
      - dist/

# --- Stage: Build Documentation ---
.build-docs-common:
  stage: docs
  image: ghcr.io/astral-sh/uv:bookworm
  needs: []
  extends:
    - .ipp_lnx_x86_64_cpu_micro
  artifacts:
    paths:
      - public
  script:
    - uv run --extra docs sphinx-build -W -b html docs docs/_build/html
    - mv docs/_build/html/ ./public/

# Merge requests: Build documentation and save as an artifact
# A link to the generated documentation is added to the merge request.
merge request docs:
  extends:
    - .build-docs-common
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  timeout: 10m
  environment:
    name: review/$CI_MERGE_REQUEST_IID
    url: https://$CI_PROJECT_ROOT_NAMESPACE.$CI_PAGES_DOMAIN/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/public/index.html
  after_script:
    - echo "View the website at https://$CI_PROJECT_ROOT_NAMESPACE.$CI_PAGES_DOMAIN/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/public/index.html"

doctest:
  stage: docs
  image: ghcr.io/astral-sh/uv:bookworm
  needs: []
  extends:
    - .ipp_lnx_x86_64_gpu
  script:
    - uv run --extra docs sphinx-build -W -b doctest docs docs/_build/doctest

# Build documentation and publish on gitlab-master
# This only runs in the default branch pipeline. The "pages" name is special for GitLab.
pages:
  extends:
    - .build-docs-common
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  timeout: 10m
  environment:
    name: GitLab Pages
    deployment_tier: staging
    url: $CI_PAGES_URL
